server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath*:com/yy/admin/mapper/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoints:
    jmx.exposure.include: "*"
    web:
      exposure.include: "*"
      base-path: /actuator
  endpoint.shutdown.enabled: true

spring:
  mvc:
    static-path-pattern: /static/**
  #  cache:
  #    type: redis
  #    redis:
  #      time-to-live: 1h
  #  redis:
  #    host: localhost
  #    #    password:
  #    timeout: 5000
  #    port: 6379
  #    jedis:
  #      pool:
  #        max-active: 10000
  #        max-idle: 50
  #        min-idle: 8
  #数据源 配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.153:3306/testdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    druid:
      # 初始化大小，最小，最大
      initial-size: 10
      min-idle: 10
      max-active: 50
      # 配置获取连接等待超时的时间,单位是毫秒
      max-wait: 60000
      # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      filter:
        # 配置StatFilter
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 3000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
